# Site settings
baseurl = "https://weihnachtsprojekt.github.io/Weihnachtsprojekt/"
languageCode = "de-de"
title = "Weihnachtsprojekt"
theme = "hugrid"
publishDir = "docs"
# Enter your tracking code to enable Google Analytics

contentdir = "content"
datadir = "data"
layoutdir = "layouts"

[params]
    # Meta
    title = "Weihnachtsprojekt"
    subtitle = "Lasst uns was bewirken"
    author = ""
    description = ""
    keywords = ""

    # Body background color
    bodybgcolor = "#f9f9f9"

    # Preview container button text
    buttontext = "Zum Projekt"

    # Footer text
    footertext = "Made by [Codrops](http://tympanus.net/codrops/2013/03/19/thumbnail-grid-with-expanding-preview/), [Hugo](http://gohugo.io) and [me](https://github.com/aerohub)"

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']